# Generated by Django 3.2.5 on 2023-05-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='barcodes/')),
                ('pdf', models.FileField(upload_to='barcodes/')),
            ],
        ),
    ]
