# Generated by Django 3.2.5 on 2023-05-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barcode',
            name='image',
        ),
        migrations.AlterField(
            model_name='barcode',
            name='number',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='pdf',
            field=models.URLField(max_length=255),
        ),
    ]
